import Generic from '../components/Generic';
export const category = [
  {
    id: 1,
    title: 'Exchange',
    path: '/exchange',
    description: '',
    Component: Generic,
  },
  {
    id: 2,
    title: 'Institutional & VIP Services',
    path: '/institutional-vip-services',
    description: '',
    Component: Generic,
  },
  {
    id: 3,
    title: 'Cloud',
    path: '/cloud',
    description: '',
    Component: Generic,
  },
  {
    id: 4,
    title: 'Launchpad',
    path: '/launchpad',
    description: '',
    Component: Generic,
  },
  {
    id: 5,
    title: 'Binance Gift Card',
    path: '/binance-gift-card',
    description: '',
    Component: Generic,
  },
  {
    id: 6,
    title: 'Academy',
    path: '/academy',
    description: '',
    Component: Generic,
  },
  {
    id: 7,
    title: 'Learn & Earn',
    path: '/learn-earn',
    description: '',
    Component: Generic,
  },
  {
    id: 8,
    title: 'DEX',
    path: '/dex',
    description: '',
    Component: Generic,
  },
  {
    id: 9,
    title: 'Research',
    path: '/research',
    description: '',
    Component: Generic,
  },
  {
    id: 10,
    title: 'Binance Live',
    path: '/binance-live',
    description: '',
    Component: Generic,
  },
  {
    id: 11,
    title: 'Broker',
    path: '/broker',
    description: '',
    Component: Generic,
  },
  {
    id: 12,
    title: 'Charity',
    path: '/charity',
    description: '',
    Component: Generic,
  },
  {
    id: 13,
    title: 'Labs',
    path: '/labs',
    description: '',
    Component: Generic,
  },
  {
    id: 14,
    title: 'Trust Wallet',
    path: '/trust-wallet',
    description: '',
    Component: Generic,
  },
  {
    id: 15,
    title: 'APIs',
    path: '/apis',
    description: '',
    Component: Generic,
  },
];
